name: nuclei scan

on:
  schedule:
    - cron: '0 */3 * * *'  # every 3 hours
  workflow_dispatch:
    inputs:
      custom_target:
        description: 'Specify a custom target (optional)'
        required: false
        default: ''
      subenum:
        description: 'Enable subdomain enumeration'
        required: false
        default: 'true'
        type: boolean

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.21.0'
        cache: false

    - name: Install Security Tools
      run: |
        go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
        go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
        go install -v github.com/tomnomnom/assetfinder@latest

        nuclei -update-templates

    - name: Clone Custom Nuclei Templates
      run: |
        git clone https://github.com/emadshanab/Nuclei-Templates-Collection.git custom-templates
        mkdir -p ~/.nuclei-templates/custom
        cp -r custom-templates/* ~/.nuclei-templates/custom

    - name: Deduplicate Nuclei Templates
      run: |
        mkdir -p ~/.nuclei-templates/combined

        find ~/.nuclei-templates -mindepth 1 -maxdepth 1 ! -name 'combined' -exec cp -r {} ~/.nuclei-templates/combined/ \;

        echo "Templates deduplicated into ~/.nuclei-templates/combined"

    - name: Prepare Target
      run: |
        if [ -n "${{ github.event.inputs.custom_target }}" ]; then
          TARGET="${{ github.event.inputs.custom_target }}"
          echo "$TARGET" > targets.txt
        else
          curl -s https://raw.githubusercontent.com/arkadiyt/bounty-targets-data/main/data/wildcards.txt | shuf -n 1 > targets.txt
        fi

    - name: Subdomain Enumeration
      if: ${{ github.event.inputs.subenum != 'false' }}
      run: |
        cat targets.txt | subfinder -all -o subdomains.txt
        cat targets.txt | assetfinder --subs-only >> subdomains.txt
        sort -u subdomains.txt -o subdomains.txt
        SUBDOMAIN_COUNT=$(wc -l < subdomains.txt)
        echo "Subdomains found: $SUBDOMAIN_COUNT"

    - name: Nuclei Vulnerability Scanning
      run: |
        TARGET_FILE=$([ -f subdomains.txt ] && echo "subdomains.txt" || echo "targets.txt")
        
        nuclei \
          -l $TARGET_FILE \
          -c 50 \
          -stats \
          -timeout 10 \
          -retries 2 \
          -rl 150 \
          -o vulnerabilities.txt \
          -s high,critical \
          -es info,low \
          -t ~/.nuclei-templates/combined/ \
          -j \
          -json-export nuclei-results.json

        VULN_COUNT=$(grep -c '"severity": "high\|"severity": "critical"' nuclei-results.json || echo 0)
        echo "High/Critical Vulnerabilities found: $VULN_COUNT"

    - name: Prepare Notification
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        TARGET=$(cat targets.txt)
        SUBDOMAIN_COUNT=$([ -f subdomains.txt ] && wc -l < subdomains.txt || echo "0")
        VULN_COUNT=$(grep -c '"severity": "high\|"severity": "critical"' nuclei-results.json || echo "0")

        MESSAGE="🚨 *Vulnerability Scan Report* 🚨
        Target: *$TARGET*
        Subdomains Found: *$SUBDOMAIN_COUNT*
        High/Critical Vulnerabilities: *$VULN_COUNT*"

        if [ -s vulnerabilities.txt ]; then
          curl -F "chat_id=$TELEGRAM_CHAT_ID" \
               -F "document=@vulnerabilities.txt" \
               -F "caption=$MESSAGE" \
               -F "parse_mode=Markdown" \
               "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendDocument"
        else
          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
               -d chat_id=$TELEGRAM_CHAT_ID \
               -d text="$MESSAGE" \
               -d parse_mode=Markdown
        fi

    - uses: actions/upload-artifact@v4
      with:
        name: scan-results
        path: |
          vulnerabilities.txt
          nuclei-results.json
          subdomains.txt
